

  SBDSP is a Pascal Unit that allows one to utilize the FULL power of the
Sound Blaster's Digital channel. At one stage in my game programming projects
I realized that I was going to need digital sound and music in my games!
After all, the PC Speaker was just NOT going to be good enough for a
production level game (BTW, I still haven't released anything as of this
writing), but to my dismay, all of the books and literature seemed to use the
darn libraries that Creative ships with "genuine" (albeit noisy) Sound Blasters.
This meant that people without the drivers would not be able to run my
programs! So, I contacted Creative, and found out that their developer's kit
costs 100 U.S Dollars! I then hunted on the Internet, and found a few docs
here and there, and I eventually managed to create the SBDSP and SBFM
libraries. Anyways, I am releasing this unit to the public for those who need
the capability of digital sound, and my code surpasses the information found
in the SDK made by Creative. There are 2 Programs attached to the SBDSP unit
itself, and those illustrate how to play back and record a sample (from
Disk).

{------------------------- snip, snip ----------------------------}

ENCODED SBDSP2B.ZIP FILE REMOVED.  PLEASE DOWNLOAD EITHER THE 
ATTACHMENT OR THE COMPLETE ZIP FILE.