Unit Graphics;
{----------------------------------------------------------------------------}
{  Graphics : An implementation of a graphics library. All standard VGA and  }
{             VESA modes are supported. A Tseng Labs ET4000 specific         }
{             implementation is also included.                               }
{****************************************************************************}
{  Author            : Menno Victor van der star                             }
{  E-Mail            : s795238@dutiwy.twi.tudelft.nl                         }
{  Developed on      : 08-06-'95                                             }
{  Last update on    : 07-09-'95                                             }
{  Status            : All modes are operational but some of the less        }
{                      frequently used ones are extremely slow because they  }
{                      use BIOS calls instead of mode-specific code.         }
{                      The NOT, AND, OR and XOR modes are not yet supported. }
{                      Due to GPF-faults, Vesa is defined for, and can       }
{                      subsequently only be used in Real mode.               }
{  Future extensions : - X-MODE specific implementation                      }
{                      - Support for fillpattern in BoundaryFill/FloodFill   }
{                      - Support for linestyles                              }
{                      - Support for write-modes other than NORMAL           }
{                      - More graphic functions like :                       }
{                         * Convex Hull                                      }
{                         * Etcetera...                                      }
{                      - Implementations for other chip-sets                  }
{----------------------------------------------------------------------------}

SWAG NOTE :

This file was too big to include in SWAG as is.  Use XX3402 to decode the
attached.

{------------------------- snip, snip ----------------------------}

ENCODED G3.ZIP FILE REMOVED.  PLEASE DOWNLOAD EITHER THE 
ATTACHMENT OR THE COMPLETE ZIP FILE.