(*
****************************************************************

TITLE    : KOJAKVGA VERSION 3.3

FILENAME : KOJAKVGA.PAS

AUTHOR   : SCOTT TUNSTALL B.Sc (aka Lt. Kojak)
	   Creator of the saddest games this century....

FINISH   : REV 3.1:  18TH AUGUST 1996 (A lot of bugs were left
DATE       in this version: You might have it in the SWAG if
	   you're unlucky!)

	   3.2:  26TH OCTOBER 1996

	   3.3:  24TH NOVEMBER 1996 ( 3.2 w/ bug fixes &
					  optimisations)

TESTING  : TESTED ON A INTEL P133 W/ CIRRUS LOGIC 5446 PCI
	   GRAPHICS CARD (guess who upgraded then? :) ),
	   24MB OF RAM (when the bast decides to work),
           1.2 Gb HARD DISK. And fluffy dice, magic Tree etc.
           And go faster stripes.

	   AREAFILL & PCX SAVE ROUTINE "OMISSIONS"
	   FIXED AND TESTED - THIS TIME THEY WORK PROPERLY !.

****************************************************************
*)



{
LEGAL STUFF:

No unauthorised modification, extraction or reproduction of any
part of this unit source allowed, except for inspection
purposes.

You are allowed to compile this unit and use it in tandem with
your own software, as long as you mention my name and KOJAKVGA
in the credits.

In the event you discover any bugs, you are permitted to fix
them, as long as you post the fixes to SWAG.



DISCLAIMER:
-----------

Use this unit at your OWN RISK. If your PC dies after using
KOJAKVGA, don't blame me. KOJAKVGA works fine on my PC.
(But then again, I would say that, cos if I didn't, no-one
would use this would they? But it works!)
}

{ ------------------------- snip, snip ----------------------------}

ENCODED KKK.ZIP FILE REMOVED.  PLEASE DOWNLOAD EITHER THE 
ATTACHMENT OR THE COMPLETE ZIP FILE.