
Here, add this great graphic unit to SWAG. You need to decode it with
xx3402 though.

--
Brad Allred
E-Mail: lallred@utah.uswest.net
Home: http://www.geocities.com/SiliconValley/Pines/3620/index.htm

{The VGA2 graphics unit is a FAST and EASY unit for Turbo Pascal Programmers,
Using this unit will realy help your programming, but it is only for
320x200, 256 color mode. I don't think you can go much
faster than this. This unit has RLE sprite support, one Virtual screen,
example programs, a PCX loader, custom fonts, and everything you could
possibly need to make a great game. As far as I know, it is Bug free, but
there could always be something I've missed, and also, if you wan't to add
something to this unit feel free to do so. IF you do send it to me at
                       lallred@uath.uswest.net


{------------------------- snip, snip ----------------------------}

ENCODED VGA2.ZIP FILE REMOVED.  PLEASE DOWNLOAD EITHER THE 
ATTACHMENT OR THE COMPLETE ZIP FILE.
