
{ SWAG NOTE :  The sources for these are included as XX3402 encoded at
  the end of this file !! }

 Anyway, I've 'cut' together this contribution. I believe.. well -hope-
 that this code will be of use to some of the pascal-programmers out
 there. It consists of a low-level unit to manipulate textmodes, a
 mid-level unit for some simple Windows-boxes, a demo-program for those
 two units and lastly another Input() routine (sort of version 2.0 of the
 one I submitted over a year ago.)

 If you could keep the STMR_LOW, STMR_MID, and STMRDEMO source in the
 same .SWG file that would be great (so people wouldn't have to look for them
 all over the place).

 {
  STMRDEMO v0.1.0 - (C)1996 Eddy L O Jansson / DFR Research & Engineering

 Desc:

  This is a small demonstration of some of the STMR_LOW & MID routines.

 Notes:

  This program will demo screen-modes 3 (80x25 and 80x50), $55 (132x25)
  and $54 (132x43). The last two modes may not be available on your
  graphics-card.
}

{------------------------- snip, snip ----------------------------}

ENCODED STMR.ZIP FILE REMOVED.  PLEASE DOWNLOAD EITHER THE 
ATTACHMENT OR THE COMPLETE ZIP FILE.