
{
(My english is terrible so you have to excuse me for that.. ;-)

I would like to contribute this to SWAG. I have added also some examples.
If it's too long you can remove the examples. I hope that by contributing
this that all those hours of programming were not wasted... ;) I hope
you accept this contribute. (if so please let me know).

Tristan van Styn

(end of message)
----CUT-CUT-CUT---------------------------------------------------------------
I have more stuff concerning these units like: more examples..
bmp, etc. etc. e-mail me if you want to have them...

If someone have information about how to program SCSI or APSI
(in DOS and Windows) so I can add the CD-ROM part to these units!
(for some reason the SCSI drivers mostly work better then MSCDEX)..
please e-mail me...

----CUT-CUT-CUT---------------------------------------------------------------}

ENCODED CDROM.ZIP FILE REMOVED.  PLEASE DOWNLOAD EITHER THE 
ATTACHMENT OR THE COMPLETE ZIP FILE.

