{+--------------------------------------------------------------------------+
 | Class:       TTISearch  ( insensitive TurboSearch)
 | Created:     8.97
 | Author:      Martin Waldenburg
 | Copyright    1997, all rights reserved.
 | Description: A very fast case insensitive search engine, based on an article in the German
 |              magazine c't (8/97). However "Look_at" isn't implemented.
 |              The original is in 'C '.
 | Version:     1.4
 | Status:      FreeWare
 | It's provided as is, without a warranty of any kind.
 | You use it at your own risc.
 | E-Mail me at Martin.Waldenburg@t-online.de
 +--------------------------------------------------------------------------+}

{ {------------------------- snip, snip ----------------------------}

ENCODED TTISEAR.ZIP FILE REMOVED.  PLEASE DOWNLOAD EITHER THE 
ATTACHMENT OR THE COMPLETE ZIP FILE.
