{+--------------------------------------------------------------------------+
 | Component:   TTokenList
 | Created:     12.06.97
 | Author:      Martin Waldenburg
 | Copyright    1997, all rights reserved.
 | Description: TTokenList is a general tokenizer, very fast.
 |              It contains a faster replacement for StrScan.
 | Version:     1.2
 | State:       FreeWare
 +--------------------------------------------------------------------------+}
 { Disclaimer:
   This is provided as is, expressly without a warranty of any kind.
   You use it at your own risc.}

{ {------------------------- snip, snip ----------------------------}

ENCODED MWTOKEN.ZIP FILE REMOVED.  PLEASE DOWNLOAD EITHER THE 
ATTACHMENT OR THE COMPLETE ZIP FILE.
