{--------------------------------------------------------------------}
{ TmwDList V 1.0                                                     }
{ Written by Martin Waldenburg 1996.                                 }
{ Copyright by Martin Waldenburg 1996. All rights reserved.          }
{ This is FreeWare.                                                  }
{ Not testet with Delphi1.                                           }
{ It's provided as is, without a warranty of any kind.               }
{ You use it at your own risc.                                       }
{ You may use and distribute it freely.                              }
{ But You may not say it's your work                                 }
{ If you distribute it you must provide all Files.                   }
{--------------------------------------------------------------------}
{ This Component demonstrates the implementation and use of a        }
{ sortable doubly linked list using MergeSort.                                }
{ I couldn't find a doubly linked list implemented as a component,   }
{ I wrote it myself.                                                 }
{ I implemented this with MergeSort because I've wasted so mucht     }
{ time waiting for sorting.                                          }
{ Mergesort is most efficient if used with linked lists, in which    }
{ case it comes very close to the theoretically most efficient       }
{ sorting algorithm possible.                                        }
{ This is only a simple implementation, you can double the speed     }
{ verry easy.  However it's fast, fast, fast.                        }
{ Take care only allocating enough memory that Windows doesn't swap. }
{ In this case you must sort parts, save to disc, then merge the     }
{ disc files                                                         }
{ Enjoy it's free.                                                   }
{--------------------------------------------------------------------}
{ 

MWSORT.ZIP WAS REMOVED.  IT HAS A DECODE ERROR.  SEE THE PAGE ON THE
ATTACHMENT LINK.
