{+--------------------------------------------------------------------------+
 | Unit:        mwIPos
 | Created:     8.97
 | Author:      Martin Waldenburg
 | Copyright    1997, all rights reserved.
 | Description: Two simple and effective case insensitive "Pos" functions.
 |              The typecast in the parameters is a bit uncomfortable, but
 |              otherwise it would be significant slower.
 | Version:     1.6
 | Status:      FreeWare
 | Disclaimer:
 | This is provided as is, expressly without a warranty of any kind.
 | You use it at your own risc.
 +--------------------------------------------------------------------------+}
{ ------------------------- snip, snip ----------------------------}

ENCODED MWIPOS.ZIP FILE REMOVED.  PLEASE DOWNLOAD EITHER THE 
ATTACHMENT OR THE COMPLETE ZIP FILE.