For win95/delphi 2.0 and up.

Unit MyCom

// A testcomponent for communicating with RS-232
// developed by JKl productions
//
// This is freware and mainly produced, because I
// couldn't find any such component with source for
// Delphi.
// The product is meant as a test component, and
// errors etc. may still occur but I haven't found
// anything serious.
// There is still lot's of space for improvement etc.
// and you are welcome to update and use this unit.
//

Commu, a testform to check if everything is working correctly.
XON/XOFF check is not yet implemented.
So good luck with communication.

For comments and ideas, adress to
Jesper Kleis
Email: CAVA@Image.DK

{ ------------------------- snip, snip ----------------------------}

ENCODED COM.ZIP FILE REMOVED.  PLEASE DOWNLOAD EITHER THE 
ATTACHMENT OR THE COMPLETE ZIP FILE.