{$G+}
Unit Windows;

{
Really net graphics unit to emulate graphics windows with buttons just
like WIN95.  See the XX3402 code at the end for more information.


Email me if there is something you want to know...
  Tommy Andersen
  X400: /S=tommy/G=andersen/P=maxware/A=telemax/C=no
  Internet: tommy.andersen@maxware.no

Limitations:
  Only 128 windows.
  Only 128 buttons.
  Only 128 windows.
  Only 256 colors.
  Only 320x200 resolution and windows.
}

{ the following contains addition files that should be included with this
  file.  To extract, you need XX3402 available with the SWAG distribution.

  1.     Cut the text below out, and save to a file  ..  filename.xx
  2.     Use XX3402  :   xx3402 d filename.xx
  3.     The decoded file should be created in the same directory.
  4.     If the file is a archive file, use the proper archive program to
         extract the members.

{ ------------------            CUT              ----------------------}

{------------------------- snip, snip ----------------------------}

ENCODED WIN.ZIP FILE REMOVED.  PLEASE DOWNLOAD EITHER THE 
ATTACHMENT OR THE COMPLETE ZIP FILE.