

			  LCD-style Fonts for the BGI



	 I release these fonts as freeware.

	 These	are  the  first  and the last fonts  I	wrote  using  the
      Borland's  font  editor: I realized that this way of  creating  BGI
      fonts  takes  too much time and patience.  For this reason  I  have
      written  "Easy  Fonts v1.0 for Windows", a program  that	instantly
      converts	any TrueType font to the CHR format used by the BGI.  You
      can find it on my home page.


      These are my addresses:

      E-mail:  pnavato@poboxes.com
	       pnavato@geocities.com
	       Pino Navato, 2:335/225.18  (The Bits BBS, Fidonet)

      WWW:     www.poboxes.com/pnavato
	       (currently forwards to
		 www.geocities.com/SiliconValley/4421)

      Mail:    Pino Navato
	       Via Pittore, 164
	       80046 S.Giorgio a Cremano (NA)
	       ITALY




			   *	 *     *     *	   *

{ {------------------------- snip, snip ----------------------------}

ENCODED LCDFONTS.ZIP FILE REMOVED.  PLEASE DOWNLOAD EITHER THE 
ATTACHMENT OR THE COMPLETE ZIP FILE.